apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-02-20T12:37:00Z"
  generation: 17
  labels:
    app: haproxy
    app.kubernetes.io/component: haproxy
    app.kubernetes.io/instance: haproxy
  name: haproxy
  namespace: plain-scale
  resourceVersion: "12337974"
  selfLink: /apis/apps.openshift.io/v1/namespaces/plain-scale/deploymentconfigs/haproxy
  uid: b0262bf5-fceb-462e-bfac-56fd17b5fded
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: haproxy
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: haproxy
    spec:
      containers:
      - image: haproxy:1.9.14
        imagePullPolicy: Always
        name: haproxy
        resources: {}
        securityContext:
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy
          name: config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        test.role: router
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: haproxy
        name: config
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - haproxy
      from:
        kind: ImageStreamTag
        name: haproxy:1.9.0
        namespace: plain-scale
    type: ImageChange
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: "2020-02-24T12:14:14Z"
    lastUpdateTime: "2020-02-24T12:14:14Z"
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  - lastTransitionTime: "2020-02-24T12:14:25Z"
    lastUpdateTime: "2020-02-24T12:14:25Z"
    message: replication controller "haproxy-13" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - imageTrigger:
        from:
          kind: DockerImage
          name: haproxy:1.9.14
      type: ImageChange
    message: image change
  latestVersion: 13
  observedGeneration: 17
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
