apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: basic-install
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        nodeSelector:
          test.role: router
        hpaSpec:
          minReplicas: 1
          maxReplicas: 1
    cni:
      namespace: kube-system
      enabled: true
  values:
    cni:
      cniBinDir: /var/lib/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      chained: false
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni