global:
  # TODO: remove me, using CNI
  proxy_init:
    # alternatively use docker.io/maistra/proxy-init-centos7:1.0.0 on RHEL7 compute nodes
    image: docker.io/maistra/proxy-init-ubi8:1.0.0
  proxy:
    # Disable autoinject as that would by default affect -deploy and -build pods
    autoInject: disabled
    # Use privileged access with proxy-init-centos7
    privileged: true
    accessLogFile: ""
    concurrency: 4
    resources:
      limits:
        cpu: 4000m
        memory: 2048Mi
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false


sidecarInjectorWebhook:
  enabled: true
  rewriteAppHTTPProbe: false

pilot:
  autoscaleEnabled: false
  traceSampling: 0.0
  resources:
    requests:
      cpu: 10m
      memory: 100Mi

mixer:
  policy:
    enabled: false

  telemetry:
    enabled: false

grafana:
  enabled: true

tracing:
  enabled: false

kiali:
  enabled: true
  createDemoSecret: true

gateways:
  istio-ingressgateway:
    autoscaleEnabled: false
    resources:
      # Ideally unlimited
      limits:
        cpu: 32
        memory: 64Gi
      requests:
        cpu: 10m
        memory: 40Mi

  istio-egressgateway:
    enabled: true
    autoscaleEnabled: false
    resources:
      # Ideally unlimited
      limits:
        cpu: 32
        memory: 64Gi
      requests:
        cpu: 10m
        memory: 40Mi

istio_cni:
  enabled: false