apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: scale-test
parameters:
- name: WILDCARD_DOMAIN
  description: "Wildcard domain that will be redirected to Istio Ingress Gateway"
  value: istio.router.default.svc.cluster.local
- name: NAMESPACE
  description: "Test namespace"
  value: istio-scale
- name: ISTIO_NAMESPACE
  description: "Test namespace"
  value: istio-system
- name: APP_LABEL
  description: Value for 'app' label on the pods.
  value: app
objects:
# Maistra creates route automatically when ior_enabled: true
# - apiVersion: route.openshift.io/v1
#   kind: Route
#   metadata:
#     name: istio-ingress
#     namespace: ${ISTIO_NAMESPACE}
#   spec:
#     host: subdomain.${WILDCARD_DOMAIN}
#     # istio-ingressgateway has several ports. Without specifying the port explicitly
#     # it would loadbalance between those ports round-robin.
#     port:
#       targetPort: 80
#     tls:
#       # passthrough + allow would be better but not possible ATM
#       termination: edge
#       insecureEdgeTerminationPolicy: Allow
#     to:
#       kind: Service
#       name: istio-ingressgateway
#       weight: 100
#     wildcardPolicy: Subdomain
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: app-gateway
    namespace: ${NAMESPACE}
  spec:
    selector:
      istio: ingressgateway # use Istio default gateway implementation
    servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
      # Catch-all route not allowed in Maistra
      - "*.${WILDCARD_DOMAIN}"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_LABEL}
    name: app
    namespace: ${NAMESPACE}
  spec:
    ports:
    # The port number has to be hardcoded as templates don't allow
    # integer parameters and definition with string port fail with
    #    Error from server: unrecognized type: int32
    - name: http-4040
      port: 4040
      protocol: TCP
      targetPort: 4040
    - name: db-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: ${APP_LABEL}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: variant
    namespace: ${NAMESPACE}
  spec:
    hosts:
    - app.${WILDCARD_DOMAIN}
    - app.${NAMESPACE}.svc.cluster.local
    gateways:
    - app-gateway
    http:
    - match:
      - headers:
          x-variant:
            exact: stable
      route:
      - destination:
          host: app
          port:
            number: 4040
          subset: stable
    - match:
      - headers:
          x-variant:
            exact: canary
      route:
      - destination:
          host: app
          port:
            number: 4040
          subset: canary
    - match:
      - headers:
          x-variant:
            exact: mirror
      route:
      - destination:
          host: app
          port:
            number: 4040
          subset: stable
      mirror:
        host: app
        port:
          number: 4040
        subset: canary
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: variant
    namespace: ${NAMESPACE}
  spec:
    host: app.${NAMESPACE}.svc.cluster.local
    trafficPolicy:
      loadBalancer:
        simple: RANDOM
    subsets:
    - name: stable
      labels:
        app.variant: stable
    - name: canary
      labels:
        app.variant: canary
