- hosts: backend
  gather_facts: false
  tasks:
  - name: Switch namespace
    command: oc project {{ namespace }}
  - include_tasks: shutdown-openshift.yaml
  - name: Pick temp file
    tempfile:
      prefix: resources-
      suffix: .yaml
    register: resources
  - name: Generate resources
    template:
      src: resources.yaml.j2
      dest: "{{ resources.path }}"
  - name: Apply resources
    command: oc apply -f "{{ resources.path }}"
  - name: Wait for pods to come up
    shell: oc get po -l app=={{ app_label }} -n {{ namespace }} --no-headers | grep '2/2' | wc -l
    register: ready_pods
    until: ready_pods.stdout | int == (num_apps | int) * (pods_per_app | int)
    delay: 5
    retries: 30
- hosts: hyperfoil-controller
  vars:
    hyperfoil_role: controller
  roles:
  - hyperfoil.hyperfoil_setup
- hosts: hyperfoil-agent
  vars:
    hyperfoil_role: agent
  roles:
  - hyperfoil.hyperfoil_setup
