- hosts: openshift
  gather_facts: false
  tasks:
  - name: Login
    when: oc_username is defined and oc_password is defined
    command: oc login --username={{ oc_username }} --password={{ oc_password }}
  - name: Switch namespace
    command: oc project {{ namespace }}
  - include_tasks: shutdown-openshift.yaml
  - name: Pick temp file
    tempfile:
      prefix: resources-
      suffix: .yaml
    register: resources
  - name: Generate resources
    template:
      src: resources.yaml.j2
      dest: "{{ resources.path }}"
  - name: Apply resources
    command: oc apply -f "{{ resources.path }}"
  - name: Drop temp file
    file:
      path: "{{ resources.path }}"
      state: absent
  - name: Generate deployment configs in batches
    include_tasks: generate-dc.yaml
    vars:
      batch_apps: "{{ [ (num_apps | int) - app_first + 1, 10 ] | min }}"
    loop: "{{ range(1, (num_apps | int) + 1, 10) | list }}"
    loop_control:
      loop_var: app_first
- hosts: hyperfoil-controller
  vars:
    hyperfoil_role: controller
  roles:
  - hyperfoil.hyperfoil_setup
- hosts: hyperfoil-agent
  vars:
    hyperfoil_role: agent
  roles:
  - hyperfoil.hyperfoil_setup
