apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: mesh-control-plane
spec:
  istio:
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        enabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: true
        resources:
          requests:
            cpu: 16
            memory: 2Gi
    global:
      proxy:
        autoInject: disabled
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
    grafana:
      enabled: false
    kiali:
      enabled: false
    mixer:
      policy:
        autoscaleEnabled: false
        enabled: false
      telemetry:
        autoscaleEnabled: false
        enabled: false
    pilot:
      autoscaleEnabled: false
      traceSampling: 0
    tracing:
      enabled: false
      jaeger:
        enabled: false
        template: all-in-one
    prometheus:
      ingress:
        enabled: false
  template: default
  version: v1.1
